-- MySQL Script generated by MySQL Workbench
-- Friday 27 March 2020 09:36:35 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema csdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema csdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `csdb` DEFAULT CHARACTER SET utf8 ;
USE `csdb` ;

-- -----------------------------------------------------
-- Table `csdb`.`groups_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csdb`.`groups_table` (
  `group_id` VARCHAR(30) NOT NULL,
  `group_name` VARCHAR(100) NULL,
  PRIMARY KEY (`group_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `csdb`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csdb`.`login` (
  `user_id` VARCHAR(16) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `group_group_id` VARCHAR(30) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`, `group_group_id`),
  CONSTRAINT `fk_user_group`
    FOREIGN KEY (`group_group_id`)
    REFERENCES `csdb`.`groups_table` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `csdb`.`city_master`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csdb`.`city_master` (
  `city_id` VARCHAR(3) NOT NULL,
  `city_name` VARCHAR(255) NULL,
  PRIMARY KEY (`city_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `csdb`.`country_master`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csdb`.`country_master` (
  `country_code` VARCHAR(3) NOT NULL,
  `country_name` VARCHAR(255) NULL,
  `latitude` DOUBLE NULL,
  `longitude` DOUBLE NULL,
  PRIMARY KEY (`country_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `csdb`.`state_master`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csdb`.`state_master` (
  `state_id` VARCHAR(3) NOT NULL,
  `state_name` VARCHAR(255) NULL,
  `country_country_id` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`state_id`, `country_country_id`),
  CONSTRAINT `fk_state_country1`
    FOREIGN KEY (`country_country_id`)
    REFERENCES `csdb`.`country_master` (`country_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `csdb`.`district_master`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csdb`.`district_master` (
  `district_id` VARCHAR(3) NOT NULL,
  `district_name` VARCHAR(255) NULL,
  `state_state_id` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`district_id`, `state_state_id`),
  CONSTRAINT `fk_district_state1`
    FOREIGN KEY (`state_state_id`)
    REFERENCES `csdb`.`state_master` (`state_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `csdb`.`user_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csdb`.`user_info` (
  `login_user_id` VARCHAR(16) NOT NULL,
  `first_name` VARCHAR(250) NOT NULL,
  `last_name` VARCHAR(250) NULL,
  `email_id` VARCHAR(255) NULL,
  `mobile` VARCHAR(13) NULL,
  `phone` VARCHAR(20) NULL,
  `address` VARCHAR(255) NULL,
  `landmark` VARCHAR(255) NULL,
  `pin` VARCHAR(6) NULL,
  `city_master_city_id` VARCHAR(3) NULL,
  `district_master_district_id` VARCHAR(3) NULL,
  PRIMARY KEY (`login_user_id`),
  CONSTRAINT `fk_user_info_login1`
    FOREIGN KEY (`login_user_id`)
    REFERENCES `csdb`.`login` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_info_city_master1`
    FOREIGN KEY (`city_master_city_id`)
    REFERENCES `csdb`.`city_master` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_info_district_master1`
    FOREIGN KEY (`district_master_district_id`)
    REFERENCES `csdb`.`district_master` (`district_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `csdb`.`groups_table`
-- -----------------------------------------------------
START TRANSACTION;
USE `csdb`;
INSERT INTO `csdb`.`groups_table` (`group_id`, `group_name`) VALUES ('vo', 'Volunteer');
INSERT INTO `csdb`.`groups_table` (`group_id`, `group_name`) VALUES ('us', 'User');
INSERT INTO `csdb`.`groups_table` (`group_id`, `group_name`) VALUES ('or', 'Organization');
INSERT INTO `csdb`.`groups_table` (`group_id`, `group_name`) VALUES ('ts', 'Technical Staff');
INSERT INTO `csdb`.`groups_table` (`group_id`, `group_name`) VALUES ('ad', 'Admin');

COMMIT;


-- -----------------------------------------------------
-- Data for table `csdb`.`country_master`
-- -----------------------------------------------------
START TRANSACTION;
USE `csdb`;
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('﻿AD', 'Andorra', 42.546245, 1.601554);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('AE', 'United Arab Emirates', 23.424076, 53.847818);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('AF', 'Afghanistan', 33.93911, 67.709953);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('AG', 'Antigua and Barbuda', 17.060816, -61.796428);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('AI', 'Anguilla', 18.220554, -63.068615);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('AL', 'Albania', 41.153332, 20.168331);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('AM', 'Armenia', 40.069099, 45.038189);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('AN', 'Netherlands Antilles', 12.226079, -69.060087);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('AO', 'Angola', -11.202692, 17.873887);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('AQ', 'Antarctica', -75.250973, -0.071389);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('AR', 'Argentina', -38.416097, -63.616672);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('AS', 'American Samoa', -14.270972, -170.132217);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('AT', 'Austria', 47.516231, 14.550072);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('AU', 'Australia', -25.274398, 133.775136);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('AW', 'Aruba', 12.52111, -69.968338);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('AZ', 'Azerbaijan', 40.143105, 47.576927);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('BA', 'Bosnia and Herzegovina', 43.915886, 17.679076);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('BB', 'Barbados', 13.193887, -59.543198);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('BD', 'Bangladesh', 23.684994, 90.356331);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('BE', 'Belgium', 50.503887, 4.469936);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('BF', 'Burkina Faso', 12.238333, -1.561593);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('BG', 'Bulgaria', 42.733883, 25.48583);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('BH', 'Bahrain', 25.930414, 50.637772);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('BI', 'Burundi', -3.373056, 29.918886);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('BJ', 'Benin', 9.30769, 2.315834);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('BM', 'Bermuda', 32.321384, -64.75737);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('BN', 'Brunei', 4.535277, 114.727669);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('BO', 'Bolivia', -16.290154, -63.588653);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('BR', 'Brazil', -14.235004, -51.92528);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('BS', 'Bahamas', 25.03428, -77.39628);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('BT', 'Bhutan', 27.514162, 90.433601);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('BV', 'Bouvet Island', -54.423199, 3.413194);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('BW', 'Botswana', -22.328474, 24.684866);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('BY', 'Belarus', 53.709807, 27.953389);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('BZ', 'Belize', 17.189877, -88.49765);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('CA', 'Canada', 56.130366, -106.346771);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('CC', 'Cocos [Keeling] Islands', -12.164165, 96.870956);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('CD', 'Congo [DRC]', -4.038333, 21.758664);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('CF', 'Central African Republic', 6.611111, 20.939444);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('CG', 'Congo [Republic]', -0.228021, 15.827659);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('CH', 'Switzerland', 46.818188, 8.227512);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('CI', 'Côte d\'Ivoire', 7.539989, -5.54708);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('CK', 'Cook Islands', -21.236736, -159.777671);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('CL', 'Chile', -35.675147, -71.542969);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('CM', 'Cameroon', 7.369722, 12.354722);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('CN', 'China', 35.86166, 104.195397);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('CO', 'Colombia', 4.570868, -74.297333);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('CR', 'Costa Rica', 9.748917, -83.753428);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('CU', 'Cuba', 21.521757, -77.781167);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('CV', 'Cape Verde', 16.002082, -24.013197);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('CX', 'Christmas Island', -10.447525, 105.690449);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('CY', 'Cyprus', 35.126413, 33.429859);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('CZ', 'Czech Republic', 49.817492, 15.472962);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('DE', 'Germany', 51.165691, 10.451526);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('DJ', 'Djibouti', 11.825138, 42.590275);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('DK', 'Denmark', 56.26392, 9.501785);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('DM', 'Dominica', 15.414999, -61.370976);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('DO', 'Dominican Republic', 18.735693, -70.162651);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('DZ', 'Algeria', 28.033886, 1.659626);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('EC', 'Ecuador', -1.831239, -78.183406);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('EE', 'Estonia', 58.595272, 25.013607);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('EG', 'Egypt', 26.820553, 30.802498);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('EH', 'Western Sahara', 24.215527, -12.885834);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('ER', 'Eritrea', 15.179384, 39.782334);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('ES', 'Spain', 40.463667, -3.74922);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('ET', 'Ethiopia', 9.145, 40.489673);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('FI', 'Finland', 61.92411, 25.748151);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('FJ', 'Fiji', -16.578193, 179.414413);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('FK', 'Falkland Islands [Islas Malvinas]', -51.796253, -59.523613);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('FM', 'Micronesia', 7.425554, 150.550812);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('FO', 'Faroe Islands', 61.892635, -6.911806);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('FR', 'France', 46.227638, 2.213749);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('GA', 'Gabon', -0.803689, 11.609444);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('GB', 'United Kingdom', 55.378051, -3.435973);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('GD', 'Grenada', 12.262776, -61.604171);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('GE', 'Georgia', 42.315407, 43.356892);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('GF', 'French Guiana', 3.933889, -53.125782);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('GG', 'Guernsey', 49.465691, -2.585278);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('GH', 'Ghana', 7.946527, -1.023194);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('GI', 'Gibraltar', 36.137741, -5.345374);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('GL', 'Greenland', 71.706936, -42.604303);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('GM', 'Gambia', 13.443182, -15.310139);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('GN', 'Guinea', 9.945587, -9.696645);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('GP', 'Guadeloupe', 16.995971, -62.067641);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('GQ', 'Equatorial Guinea', 1.650801, 10.267895);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('GR', 'Greece', 39.074208, 21.824312);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('GS', 'South Georgia and the South Sandwich Islands', -54.429579, -36.587909);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('GT', 'Guatemala', 15.783471, -90.230759);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('GU', 'Guam', 13.444304, 144.793731);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('GW', 'Guinea-Bissau', 11.803749, -15.180413);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('GY', 'Guyana', 4.860416, -58.93018);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('GZ', 'Gaza Strip', 31.354676, 34.308825);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('HK', 'Hong Kong', 22.396428, 114.109497);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('HM', 'Heard Island and McDonald Islands', -53.08181, 73.504158);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('HN', 'Honduras', 15.199999, -86.241905);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('HR', 'Croatia', 45.1, 15.2);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('HT', 'Haiti', 18.971187, -72.285215);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('HU', 'Hungary', 47.162494, 19.503304);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('ID', 'Indonesia', -0.789275, 113.921327);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('IE', 'Ireland', 53.41291, -8.24389);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('IL', 'Israel', 31.046051, 34.851612);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('IM', 'Isle of Man', 54.236107, -4.548056);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('IN', 'India', 20.593684, 78.96288);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('IO', 'British Indian Ocean Territory', -6.343194, 71.876519);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('IQ', 'Iraq', 33.223191, 43.679291);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('IR', 'Iran', 32.427908, 53.688046);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('IS', 'Iceland', 64.963051, -19.020835);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('IT', 'Italy', 41.87194, 12.56738);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('JE', 'Jersey', 49.214439, -2.13125);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('JM', 'Jamaica', 18.109581, -77.297508);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('JO', 'Jordan', 30.585164, 36.238414);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('JP', 'Japan', 36.204824, 138.252924);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('KE', 'Kenya', -0.023559, 37.906193);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('KG', 'Kyrgyzstan', 41.20438, 74.766098);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('KH', 'Cambodia', 12.565679, 104.990963);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('KI', 'Kiribati', -3.370417, -168.734039);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('KM', 'Comoros', -11.875001, 43.872219);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('KN', 'Saint Kitts and Nevis', 17.357822, -62.782998);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('KP', 'North Korea', 40.339852, 127.510093);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('KR', 'South Korea', 35.907757, 127.766922);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('KW', 'Kuwait', 29.31166, 47.481766);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('KY', 'Cayman Islands', 19.513469, -80.566956);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('KZ', 'Kazakhstan', 48.019573, 66.923684);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('LA', 'Laos', 19.85627, 102.495496);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('LB', 'Lebanon', 33.854721, 35.862285);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('LC', 'Saint Lucia', 13.909444, -60.978893);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('LI', 'Liechtenstein', 47.166, 9.555373);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('LK', 'Sri Lanka', 7.873054, 80.771797);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('LR', 'Liberia', 6.428055, -9.429499);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('LS', 'Lesotho', -29.609988, 28.233608);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('LT', 'Lithuania', 55.169438, 23.881275);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('LU', 'Luxembourg', 49.815273, 6.129583);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('LV', 'Latvia', 56.879635, 24.603189);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('LY', 'Libya', 26.3351, 17.228331);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('MA', 'Morocco', 31.791702, -7.09262);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('MC', 'Monaco', 43.750298, 7.412841);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('MD', 'Moldova', 47.411631, 28.369885);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('ME', 'Montenegro', 42.708678, 19.37439);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('MG', 'Madagascar', -18.766947, 46.869107);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('MH', 'Marshall Islands', 7.131474, 171.184478);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('MK', 'Macedonia [FYROM]', 41.608635, 21.745275);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('ML', 'Mali', 17.570692, -3.996166);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('MM', 'Myanmar [Burma]', 21.913965, 95.956223);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('MN', 'Mongolia', 46.862496, 103.846656);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('MO', 'Macau', 22.198745, 113.543873);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('MP', 'Northern Mariana Islands', 17.33083, 145.38469);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('MQ', 'Martinique', 14.641528, -61.024174);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('MR', 'Mauritania', 21.00789, -10.940835);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('MS', 'Montserrat', 16.742498, -62.187366);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('MT', 'Malta', 35.937496, 14.375416);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('MU', 'Mauritius', -20.348404, 57.552152);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('MV', 'Maldives', 3.202778, 73.22068);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('MW', 'Malawi', -13.254308, 34.301525);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('MX', 'Mexico', 23.634501, -102.552784);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('MY', 'Malaysia', 4.210484, 101.975766);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('MZ', 'Mozambique', -18.665695, 35.529562);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('NA', 'Namibia', -22.95764, 18.49041);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('NC', 'New Caledonia', -20.904305, 165.618042);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('NE', 'Niger', 17.607789, 8.081666);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('NF', 'Norfolk Island', -29.040835, 167.954712);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('NG', 'Nigeria', 9.081999, 8.675277);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('NI', 'Nicaragua', 12.865416, -85.207229);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('NL', 'Netherlands', 52.132633, 5.291266);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('NO', 'Norway', 60.472024, 8.468946);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('NP', 'Nepal', 28.394857, 84.124008);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('NR', 'Nauru', -0.522778, 166.931503);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('NU', 'Niue', -19.054445, -169.867233);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('NZ', 'New Zealand', -40.900557, 174.885971);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('OM', 'Oman', 21.512583, 55.923255);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('PA', 'Panama', 8.537981, -80.782127);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('PE', 'Peru', -9.189967, -75.015152);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('PF', 'French Polynesia', -17.679742, -149.406843);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('PG', 'Papua New Guinea', -6.314993, 143.95555);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('PH', 'Philippines', 12.879721, 121.774017);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('PK', 'Pakistan', 30.375321, 69.345116);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('PL', 'Poland', 51.919438, 19.145136);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('PM', 'Saint Pierre and Miquelon', 46.941936, -56.27111);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('PN', 'Pitcairn Islands', -24.703615, -127.439308);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('PR', 'Puerto Rico', 18.220833, -66.590149);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('PS', 'Palestinian Territories', 31.952162, 35.233154);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('PT', 'Portugal', 39.399872, -8.224454);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('PW', 'Palau', 7.51498, 134.58252);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('PY', 'Paraguay', -23.442503, -58.443832);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('QA', 'Qatar', 25.354826, 51.183884);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('RE', 'Réunion', -21.115141, 55.536384);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('RO', 'Romania', 45.943161, 24.96676);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('RS', 'Serbia', 44.016521, 21.005859);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('RU', 'Russia', 61.52401, 105.318756);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('RW', 'Rwanda', -1.940278, 29.873888);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('SA', 'Saudi Arabia', 23.885942, 45.079162);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('SB', 'Solomon Islands', -9.64571, 160.156194);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('SC', 'Seychelles', -4.679574, 55.491977);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('SD', 'Sudan', 12.862807, 30.217636);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('SE', 'Sweden', 60.128161, 18.643501);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('SG', 'Singapore', 1.352083, 103.819836);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('SH', 'Saint Helena', -24.143474, -10.030696);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('SI', 'Slovenia', 46.151241, 14.995463);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('SJ', 'Svalbard and Jan Mayen', 77.553604, 23.670272);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('SK', 'Slovakia', 48.669026, 19.699024);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('SL', 'Sierra Leone', 8.460555, -11.779889);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('SM', 'San Marino', 43.94236, 12.457777);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('SN', 'Senegal', 14.497401, -14.452362);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('SO', 'Somalia', 5.152149, 46.199616);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('SR', 'Suriname', 3.919305, -56.027783);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('ST', 'São Tomé and Príncipe', 0.18636, 6.613081);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('SV', 'El Salvador', 13.794185, -88.89653);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('SY', 'Syria', 34.802075, 38.996815);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('SZ', 'Swaziland', -26.522503, 31.465866);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('TC', 'Turks and Caicos Islands', 21.694025, -71.797928);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('TD', 'Chad', 15.454166, 18.732207);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('TF', 'French Southern Territories', -49.280366, 69.348557);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('TG', 'Togo', 8.619543, 0.824782);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('TH', 'Thailand', 15.870032, 100.992541);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('TJ', 'Tajikistan', 38.861034, 71.276093);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('TK', 'Tokelau', -8.967363, -171.855881);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('TL', 'Timor-Leste', -8.874217, 125.727539);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('TM', 'Turkmenistan', 38.969719, 59.556278);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('TN', 'Tunisia', 33.886917, 9.537499);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('TO', 'Tonga', -21.178986, -175.198242);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('TR', 'Turkey', 38.963745, 35.243322);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('TT', 'Trinidad and Tobago', 10.691803, -61.222503);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('TV', 'Tuvalu', -7.109535, 177.64933);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('TW', 'Taiwan', 23.69781, 120.960515);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('TZ', 'Tanzania', -6.369028, 34.888822);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('UA', 'Ukraine', 48.379433, 31.16558);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('UG', 'Uganda', 1.373333, 32.290275);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('US', 'United States', 37.09024, -95.712891);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('UY', 'Uruguay', -32.522779, -55.765835);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('UZ', 'Uzbekistan', 41.377491, 64.585262);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('VA', 'Vatican City', 41.902916, 12.453389);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('VC', 'Saint Vincent and the Grenadines', 12.984305, -61.287228);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('VE', 'Venezuela', 6.42375, -66.58973);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('VG', 'British Virgin Islands', 18.420695, -64.639968);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('VI', 'U.S. Virgin Islands', 18.335765, -64.896335);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('VN', 'Vietnam', 14.058324, 108.277199);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('VU', 'Vanuatu', -15.376706, 166.959158);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('WF', 'Wallis and Futuna', -13.768752, -177.156097);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('WS', 'Samoa', -13.759029, -172.104629);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('XK', 'Kosovo', 42.602636, 20.902977);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('YE', 'Yemen', 15.552727, 48.516388);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('YT', 'Mayotte', -12.8275, 45.166244);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('ZA', 'South Africa', -30.559482, 22.937506);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('ZM', 'Zambia', -13.133897, 27.849332);
INSERT INTO `csdb`.`country_master` (`country_code`, `country_name`, `latitude`, `longitude`) VALUES ('ZW', 'Zimbabwe', -19.015438, 29.154857);

COMMIT;

